export const ADD_VISITOR_CONSTANTS = {
  DATE: "Date",
  VISIT_TYPE: "Visit type",
  NAME_REQ: "Name is required",
  NAME_INVALID: "Name is invalid",
  EMAIL_REQ: "Email is required",
  EMAIL_INVALID: "Email is invalid",
  ORG_REQ: "Organization is required",
  ORG_INVALID: "Organization is invalid",
  CARD_REQ: "Card is required",
  PHONE_REQ: "Phone is required",
  TO_MEET: "To meet",
  PHONE_INVALID: "Phone is invalid",
  ID_PROOF_REQ: "ID Proof is required",
  ID_PROOF_INVALID: "ID Proof is invalid",
  ID_PROOF_NUMBER: "ID Proof Number",
  ADDRESS_REQ: "Address is required",
  ADDRESS_INVALID: "Address is invalid",
  PURPOSE_REQ: "Purpose is required",
  PURPOSE_INVALID: "Purpose is invalid",
  TO_MEET_REQ: "To meet is required",
  TO_MEET_INVALID: "To meet is invalid",
  VISIT_TYPE_REQ: "Visit type is required",
  SELECT_VISIT_TYPE: "Select visit type",
  COMMENTS_INVALID: "Comment is invalid",
  INSIDE_OFFICE: "Inside office",
  OUTSIDE_OFFICE: "Outside office",
  FNAME: "First Name",
  LNAME: "Last Name",
  ORG: "Organization",
  EMAIL: "Email",
  PHONE: "Phone",
  ADDRESS: "Address",
  ID_CARD: "ID Card",
  SAVE: "Save",
  CANCEL: "Cancel",
  NO_CARDS_AVAILABLE: "No cards available",
  PURPOSE: "Purpose",
  COMMENTS: "Comments",
  CLICK_USER_PHOTO: "Click photo of user",
  CLICK_ID_PHOTO: "Click photo of ID proof",
  OPEN_CAMERA: "Open camera",
  CAPTURE_IMAGE: "Capture",
  RESET: "Reset",
  OUTSIDE_OFFICE_MESSAGE: "Visitor added successfully. Visit is Allowed",
  INSIDE_OFFICE_MESSAGE:
    "Visitor added successfully. Approval request sent, Kindly wait for approval.",
  CLICK_PICTURE_WARNING: "Only click one picture at a time "
};
