export const ADD_VISIT_CONSTANTS = {
  SEARCH_TO_ADD_VISIT: "Please search to add a visit",
  ADD_VISIT: "Add Visit",
  TO_MEET: "To Meet",
  COMMENTS: "Comments",
  COMMENTS_INVALID: "Comments is invalid",
  PURPOSE_OF_VISIT: "Purpose of Visit",
  SELECT_CARD: "Select a Card",
  TO_MEET_REQ: "To Meet is required",
  TO_MEET_INVALID: "To Meet is invalid",
  PURPOSE_REQ: "Purpose is required",
  PURPOSE_INVALID: "Purpose is invalid",
  ID_CARD_REQ: "ID Card is required",
  VISIT_TYPE_REQ: "Visit type is required",
  NAME: "Name:",
  PHONE: "Phone:",
  ORGANIZATION: "Organization:",
  NO_CARDS_AVAILABLE: "No cards available",
  INSIDE_OFFICE: "Inside Office",
  OUTSIDE_OFFICE: "Outside Office",
  RESET: "Reset",
  OVERLAY_MSG: "Search existing visitor or add new visitor to add a visit",
  ADD_NEW_VISITOR: "Add new visitor",
  ADD_VISITOR: "Add Visitor",
  VISIT_SUCCESS_MESSAGE: "Visit added successfully. Visit is Allowed",
  VISIT_ERROR: "Couldn't add visit. Please try again.",
  VISIT_SUCCESS_APPROVAL:
    "Visit added successfully. Approval request sent, Kindly wait for approval.",
  SEARCH_VISITOR_BY_NAME: "Search for visitor by name"
};
