export const FORGOT_PASSWORD_CONSTANTS = {
  EMAIL: "Email",
  ENTER_EMAIL: "Enter Email",
  EMAIL_REQ: "Email is required",
  EMAIL_INVALID: "Email is invalid",
  SEND_OTP: "Send OTP",
  RESEND_OTP: "Resend",
  OTP: "OTP",
  OTP_REQ: "OTP is required",
  OTP_INVALID: "OTP is invalid",
  OTP_SENT_SUCCESSFULLY: "OTP sent successfully.",
  RESET_PASSWORD: "Next",
  PASSWORD: "Password",
  ENTER_PASSWORD: "Enter Password",
  PASSWORD_REQ: "Password is required",
  PASSWORD_INVALID: "Password is invalid",
  CONFIRM_PASSWORD: "Confirm Password",
  CONFIRM_NEW_PASSWORD: "Confirm New Password",
  CONFIRM_PASSWORD_REQ: "Confirm Password is required",
  CONFIRM_PASSWORD_INVALID: "Confirm Password is invalid",
  CHANGE_PASSWORD: "Change Password",
  BACK: "Back",
  RESET: "Reset",
  SAVE: "Save",
  VALID_PASSWORD_TITLE:
    "Password must contain at least one uppercase letter, one lowercase letter, one number, one special character and be at least 8 characters long.",
  NO_USER_FOUND: "No such user found. Please try again.",
  ENTER_OTP: "Please enter OTP",
  ENTER_OTP_SENT_TO_EMAIL: "Please enter the OTP sent to your email.",
  PASSWORDS_DO_NOT_MATCH: "Passwords do not match. Please try again.",
  PASSWORD_RESET_SUCCESSFULLY: "Password reset successfully."
};
