export const VISITOR_CONSTANTS = {
  DETAILS: "Details",
  ACTIONS: "Actions",
  NAME: "Name",
  FNAME: "First Name",
  LNAME: "Last Name",
  EMAIL: "Email",
  PHONE: "Phone",
  ORGANIZATION: "Organization",
  ADDRESS: "Address",
  PROFILE: "Profile",
  LOADING: "Loading...",
  GOVENRMENT_ID: "Government ID",
  VISITS: "Visits",
  PURPOSE: "Purpose",
  TO_MEET: "To Meet",
  COMMENTS: "Comments",
  DATE: "Date",
  IN_TIME: "In-Time",
  OUT_TIME: "Out-Time",
  STATUS: "Status",
  NO_VISITS_FOUND: "No Visits Found",
  NO_VISITORS_FOUND: "No Visitors Found",
  SEARCH: "Search",
  VISITORS: "Visitors",
  LOAD_MORE: "Load More",
  SEARCH_MAX_ITEMS: 11,
  NO_DATA_TO_EXPORT: "No data to export",
  SEARCH_FOR_NAME: "Search for a Name"
};
