export const VISITS_CONSTANTS = {
  TABLE_HEADING: "Visits",
  FILTER_BY_DATE: "Date range:",
  NAME: "Name",
  ORGANIZATION: "Organization",
  PHONE_NO: "PhoneNo",
  PHONE: "Phone",
  DATE: "Date",
  CHECK_IN: "In Time",
  CHECK_OUT: "Out Time",
  PURPOSE: "Purpose",
  toMeet: "To Meet",
  COMMENTS: "Comments",
  cardId: "ID Card",
  checkedInBy: "Checked In By",
  NO_VISITS_FOUND: "No Visits Found",
  WG_CARD: "WG Card",
  STATUS: "Status",
  CHECKOUT: "CheckOut",
  DETAILS: "Details",
  ACTION: "Action",
  CLEAR: "Clear",
  SEARCH: "Search",
  APPROVED_BY: "Approved By",
  APPROVAL_TIME: "Approval Time",
  NO_APPROVALS_FOUND: "No Approvals Found",
  VISITOR_CHECKED_OUT: "Visitor Checked Out Successfully!",
  ERROR_CHECKING_OUT_VISITOR: "Error Checking Out Visitor!",
  CONFIRM_MESSAGE: "Are you sure you want to proceed?",
  CONFIRMATION: "Confirmation",
  SELECT_DATE_RANGE: "Select a date range",
};
